### ISSUE TITLE
AArch64 architecture support

### ISSUE THREAD

**Issue by harry-xm** [conda-forge/r-showtext-feedstock#16]
### Comment:

Binaries for `linux_aarch64` and `osx_arm64` are missing.

**Comment by mfansler** [comment]
Conda Forge doesn't default to building those. One can trigger them to be built by submitting a PR to the `conda-forge-pinning-feedstock`, like https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5470.

Documentation:
- ["Apple Silicon builds"](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)
- ["Using `aarch_rebuild.txt`"](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-arch-rebuild-txt)

**Comment by harry-xm** [comment]
@mfansler There are specific conditions for `osx-64` in https://github.com/conda-forge/r-showtext-feedstock/blob/c163af66a993c0fe0ce94adb581cef45de6d3f55/recipe/build.sh#L2-L8.

Does this file have to be updated too?

**Comment by mfansler** [comment]
Those will get taken care of automatically by the bot. That version of the `build.sh` is rather outmoded and was the boilerplate at the time this feedstock was created. The bot will replace the whole thing with a newer boilerplate that is compatible with most R package builds.

**Comment by mfansler** [comment]
Just heads up on the migration status: the PRs for migration here will come through after https://github.com/conda-forge/r-sysfonts-feedstock/pull/12 merges.
